var calendar = [
  ["normalSchedule"],
  ["normalSchedule"],
  ["normalSchedule"],
  ["normalSchedule"],
  ["normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSmartEarly","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSmartEarly","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSmartEarly","seventhPeriodFinal","finalsWeekFirst","finalsWeekSecond","finalsWeekThird"],
  ["normalSchedule"],
  ["normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","noSchool","noSchool","noSchool","noSchool","orientationSchedule",],
  ["noSchool","noSchool","noSchool","noSchool","noSchool","noSchool","firstDaySchedule","secondDaySchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","autonomousFestival","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool"],
  ["noSchool","noSchool","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","smartNoEarly","PMAssem","noSchool","noSchool","releaseAndSmartSchedule"],
  ["normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","noSmartEarly","normalSchedule","smartNoEarly","normalSchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","normalSchedule","normalSchedule","normalSchedule","noSchool","noSchool","releaseAndSmartSchedule","normalSchedule","morningPSAT","normalSchedule"],
];
